apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
   - targetPort: 80
     port: 80
	 nodePort: 30008
  selector:
     app: RC-template //this has too be labels from metadata under spec definition of Replicaset if cluster is in replicaSet configured
     dep: Finance-Dep //myapp-RC //this has too be labels from metadata under spec definition of Replicaset if cluster is in replicaSet configured
